# Generated by Django 5.2.7 on 2025-10-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_outdoor',
            field=models.BooleanField(default=False, help_text='ติ๊กถ้าเป็นโต๊ะโซน Outdoor'),
        ),
    ]
