# Generated by Django 5.2.7 on 2025-10-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_table_is_outdoor'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='image',
            field=models.ImageField(blank=True, help_text='รูปภาพโต๊ะ', null=True, upload_to='table_images/'),
        ),
    ]
